---

- name: Flush all outstanding handlers
  meta: flush_handlers

- name: Create nodes with status "success" for testusers
  command:
    /var/www/sites/platform-data-generator/bin/pdg nodes '{"{{ item.eui64|quote }}":1}'
  with_items: "{{ platform_populate_users }}"
  when: item.active is defined and item.active == 'yes'

- name: Create nodes with status "offline" for testusers
  command:
    /var/www/sites/platform-data-generator/bin/pdg nodes '{"{{ item.eui64|quote }}":0}'
  with_items: "{{ platform_populate_users }}"
  when: item.active is defined and item.active == 'no'

- name: Create user accounts for testusers
  uri:
    url: "{{ platform_populate_api_endpoint }}"
    method: POST
    body: '{"mac_address":"{{ item.mac|quote }}","email_address":"{{ item.emailaddress|quote }}","pincode":"{{ item.pin|quote }}"}'
    body_format: json
    validate_certs: no
  with_items: "{{ platform_populate_users }}"
  when: item.mac is defined
